force-app/main/default/objects/Follows__c/Follows__c.object-meta.xml
<CustomObject>
    <description>フォローとフォローされるの関係</description>
    <label>Follows</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>follow_id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follows__c/fields/follower_id__c.field-meta.xml
<CustomField>
    <fullName>follower_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>フォロー先のユーザー</description>
    <label>follower_id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Follows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Good__c/Good__c.object-meta.xml
<CustomObject>
    <description>ユーザーとツイートの関係をつなぐための「いいね機能」</description>
    <label>Good</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>good_id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Good__c/fields/good_tweet_id__c.field-meta.xml
<CustomField>
    <fullName>good_tweet_id__c</fullName>
    <description>いいね先のツイート</description>
    <label>good_tweet_id</label>
    <referenceTo>Tweet__c</referenceTo>
    <relationshipLabel>Good</relationshipLabel>
    <relationshipName>Good</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tweet__c/Tweet__c.object-meta.xml
<CustomObject>
    <description>ツイートに関するデータ</description>
    <label>Tweet</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>TweetID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tweet__c/fields/body__c.field-meta.xml
<CustomField>
    <fullName>body__c</fullName>
    <description>ツイートの本文</description>
    <label>本文</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/commented_id__c.field-meta.xml
<CustomField>
    <fullName>commented_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>コメント先のツイートのID</description>
    <label>コメント先ツイート</label>
    <referenceTo>Tweet__c</referenceTo>
    <relationshipLabel>Tweet</relationshipLabel>
    <relationshipName>Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/like_count__c.field-meta.xml
<CustomField>
    <fullName>like_count__c</fullName>
    <label>いいね</label>
    <summaryForeignKey>Good__c.good_tweet_id__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Tweet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>タイトル</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TweetExtension.cls
public class TweetExtension {

    public String msg{get; set;}
    public Tweet__c sub_comment {get;set;}
    public Tweet__c acct;
    private ApexPages.StandardController stdController;
    // public List<Tweet__c> childrenTweets = new List<Tweet__c>();
    public TweetExtension (ApexPages.StandardController ct) {
        this.stdController = ct;
        // childrenTweets = [SELECT Id FROM Tweet__c WHERE commented_id__c = :ct.getRecord().Id];
        this.msg='表示できた！';
        sub_comment = new Tweet__c();
        this.acct =(Tweet__c)stdController.getRecord();
    }

    // 1つのツイートに対するコメントを取得（SNS_Tweet）
    public List<Tweet__c> getchildrenTweets() {
        List<Tweet__c> results = Database.query(
            'SELECT Id, body__c, CreatedById, CreatedDate, CreatedBy.Name ' +
            'FROM Tweet__c ' +
            'WHERE commented_id__c = \'' + this.stdController.getRecord().Id +'\' '
            + 'ORDER BY CreatedDate ASC' 
        );
        return results;
    }

    //自分がフォローしているユーザーのツイートを取得（SNS_Home)
    public List<Tweet__c> getFollowTweets(){
        List<Follows__c> follow_user =
            [SELECT follower_id__c,Id FROM Follows__c WHERE CreatedById = :UserInfo.getUserId()];

        Set<Id> userIds = new Set<Id>();
        for(Follows__c f:follow_user) {
            userIds.add(f.follower_id__c);
        }
        List<Tweet__c> follow_tweets =
            [SELECT title__c, body__c, like_count__c, CreatedDate, CreatedById, CreatedBy.Name FROM Tweet__c WHERE CreatedById IN :userIds ORDER BY CreatedDate DESC];

        return follow_tweets;
    }


    // ツイートの新規作成＆更新（SNS_Postで利用）
    public PageReference save(){
        System.debug(this.stdController.getRecord());

        if(((Tweet__c) this.stdController.getRecord()).id != null){
            update this.stdController.getRecord();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Successful update'));         
        }else{
            Tweet__c tweet = (Tweet__c) this.stdController.getRecord();
            insert tweet;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Successful create'));

       }
       return page.SNS_Home;

    }


    // ツイートに対するコメントをする（SNS_Tweet）
    public void comment(){
        String tweet_id = this.stdController.getRecord().Id;

        Tweet__c comment = new Tweet__c(
            commented_id__c = tweet_id,
            title__c = null
        );
        comment.body__c = sub_comment.body__c;
        insert comment;
        sub_comment = new Tweet__c();

    }

    // いいねボタンと連動してGoodレコードを作り、triggerに反応する場所（SNS_Tweet）
    public PageReference good(){
        String tweet_id = this.stdController.getRecord().Id;
        Id owner_id = UserInfo.getUserId();

        List<Good__c> result =
            [SELECT id FROM Good__c WHERE CreatedById = :owner_id AND good_tweet_id__c = :tweet_id];

        if(result.isEmpty()){
            Good__c good = new Good__c(
                good_tweet_id__c = tweet_id
            );
            insert good;
        }else{
            Good__c[] good_dlt = [SELECT id FROM Good__c WHERE CreatedById = :owner_id AND good_tweet_id__c = :tweet_id];
            delete good_dlt;
        }

        PageReference tempPages = new PageReference('/apex/SNS_Tweet?id='+tweet_id);
        tempPages.setRedirect(true);
        return tempPages;
    }

    
    //
    public List<String> accessibleFields {
        get {
            if (accessibleFields == null) {
                // Get a list (map) of all fields on the object
                Map<String, Schema.SobjectField> fields = 
                    Schema.SobjectType.Tweet__c.fields.getMap();
        
                // Save only the fields accessible by the current user 
                Set<String> availableFieldsSet = new Set<String>();
                for (String s : fields.keySet()) {
                    if (fields.get(s).getDescribe().isAccessible() 
                        // Comment out next line to show standard/system fields
                        && fields.get(s).getDescribe().isCustom()
                    ){
                            availableFieldsSet.add(s.toLowerCase());
                            if(Test.isRunningTest()) System.debug('Field: ' + s);
                    }
                }
                
                // Convert set to list, save to property
                accessibleFields = new List<String>(availableFieldsSet);
            }
            return accessibleFields;
        }
        private set;
    }



}